export const carData = {
    BMW: ['1 Series', '2 Series', '3 Series', '4 Series', '5 Series', '6 Series', '7 Series', '8 Series', 'X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'X7', 'Z4', 'M2', 'M3', 'M4', 'M5', 'M8', 'i3', 'i8', 'Other' ],
    Audi: ['A3', 'A4', 'A5', 'A6', 'A7', 'A8', 'Q3', 'Q5', 'Q7', 'Q8', 'TT', 'R8', 'S3', 'S4', 'S5', 'S6', 'S7'],
    Mercedes: ['A-Class', 'B-Class', 'C-Class', 'E-Class', 'S-Class', 'CLA', 'CLS', 'GLA', 'GLB', 'GLC', 'GLE', 'GLS', 'G-Class', 'AMG GT', 'SLC', 'SL', 'SLS', 'V-Class', 'X-Class'],
    Volkswagen: ['Polo', 'Golf', 'Passat', 'Tiguan', 'T-Roc', 'T-Cross', 'Arteon', 'Touran', 'Sharan', 'Caddy', 'Transporter', 'Caravelle', 'California', 'Amarok', 'ID.3', 'ID.4'],
    Skoda: ['Citigo', 'Fabia', 'Scala', 'Octavia', 'Superb', 'Kamiq', 'Karoq', 'Kodiaq', 'Enyaq', 'Other'],
    Toyota: ['Aygo', 'Yaris', 'Corolla', 'Camry', 'Prius', 'RAV4', 'C-HR', 'Highlander', 'Land Cruiser', 'Supra', 'GT86', 'Mirai', 'Other'],
    Honda: ['Jazz', 'Civic', 'HR-V', 'CR-V', 'e', 'NSX', 'Other'],
    Nissan: ['Micra', 'Leaf', 'Qashqai', 'X-Trail', 'Juke', 'GT-R', 'Other'],
    Ford: ['Fiesta', 'Focus', 'Mondeo', 'Mustang', 'EcoSport', 'Kuga', 'Puma', 'Edge', 'Ranger', 'Transit', 'Tourneo', 'Other'],
    Fiat: ['500', '500X', '500L', 'Panda', 'Tipo', 'Punto', 'Doblo', 'Qubo', '500e', 'Other'],
    Renault: ['Clio', 'Captur', 'Megane', 'Scenic', 'Kadjar', 'Talisman', 'Koleos', 'Zoe', 'Twizy', 'Other'],
    Peugeot: ['108', '208', '308', '508', '2008', '3008', '5008', 'Rifter', 'Traveller', 'iOn', 'Other'],
    Citroen: ['C1', 'C3', 'C4', 'C5', 'C3 Aircross', 'C4 Cactus', 'Berlingo', 'SpaceTourer', 'e-Mehari', 'Other'],
    Opel: ['Adam', 'Corsa', 'Astra', 'Insignia', 'Crossland X', 'Grandland X', 'Mokka', 'Zafira', 'Combo', 'Vivaro', 'Movano', 'Other'],
    Hyundai: ['i10', 'i20', 'i30', 'i40', 'Ioniq', 'Kona', 'Tucson', 'Santa Fe', 'Nexo', 'Other'],
    Kia: ['Picanto', 'Rio', 'Ceed', 'Stonic', 'Niro', 'Sportage', 'Sorento', 'Soul', 'Optima', 'Stinger', 'EV6', 'Other'],
    Volvo: ['S60', 'S90', 'V60', 'V90', 'XC40', 'XC60', 'XC90', 'C40', 'C70', 'Polestar', 'Other'],
    Mazda: ['2', '3', '6', 'CX-3', 'CX-30', 'CX-5', 'MX-5', 'MX-30', 'Other'],
    Mitsubishi: ['Space Star', 'ASX', 'Eclipse Cross', 'Outlander', 'L200', 'Other'],
    Suzuki: ['Swift', 'Ignis', 'Vitara', 'S-Cross', 'Jimny', 'Other'],
    Subaru: ['Impreza', 'Legacy', 'Outback', 'XV', 'BRZ', 'Forester', 'Levorg', 'Other'],
    Lexus: ['CT', 'IS', 'ES', 'LS', 'NX', 'RX', 'UX', 'LC', 'RC', 'Other'],
    AlfaRomeo: ['Giulietta', 'Giulia', 'Stelvio', '4C', 'Other'],
    Jaguar: ['XE', 'XF', 'XJ', 'F-Type', 'E-Pace', 'F-Pace', 'I-Pace', 'Other'],
    LandRover: ['Defender', 'Discovery', 'Discovery Sport', 'Range Rover', 'Range Rover Sport', 'Range Rover Velar', 'Range Rover Evoque', 'Other'],
    Porsche: ['911', '718', 'Panamera', 'Macan', 'Cayenne', 'Taycan', 'Cayman', 'Boxster', 'Other'],
    Mini: ['Hatch', 'Convertible', 'Countryman', 'Clubman', 'Electric', 'Other'],
    Tesla: ['Model S', 'Model 3', 'Model X', 'Model Y', 'Cybertruck', 'Roadster', 'Other'],
    Dacia: ['Sandero', 'Logan', 'Duster', 'Dokker', 'Lodgy', 'Spring', 'Other'],
    Seat: ['Mii', 'Ibiza', 'Leon', 'Arona', 'Ateca', 'Tarraco', 'Cupra', 'Other'],
    Other: ['Other']
  };

export default carData;